services:
  postgres:
    image: postgres:16-alpine
    container_name: to_osn_postgres
    environment:
      POSTGRES_DB: to_osn
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - to_osn_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: to_osn_redis
    ports:
      - "6379:6379"
    volumes:
      - to_osn_redisdata:/data

volumes:
  to_osn_pgdata:
  to_osn_redisdata:
